package ru.nao.bot.common.nlp;

import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

public class TagHelper {

    public final static String ROOT = "ROOT";
    public final static String ASTERICS = "*";
    public final static String ZERO = "0";
    public final static String ADJP = "ADJP";
    public final static String ADVP = "ADVP";
    public final static String CC = "CC";
    public final static String CD = "CD";
    public final static String DT = "DT";
    public final static String EX = "EX";
    public final static String FW = "FW";
    public final static String IN = "IN";
    public final static String INTJ = "INTJ";
    public final static String JJ = "JJ";
    public final static String JJR = "JJR";
    public final static String JJS = "JJS";
    public final static String LS = "LS";
    public final static String MD = "MD";
    public final static String NN = "NN";
    public final static String NNP = "NNP";
    public final static String NNPS = "NNPS";
    public final static String NNS = "NNS";
    public final static String NP = "NP";
    public final static String PDT = "PDT";
    public final static String POS = "POS";
    public final static String PP = "PP";
    public final static String PRP = "PRP";
    public final static String PRP$ = "PRP$";
    public final static String RB = "RB";
    public final static String RBR = "RBR";
    public final static String RBS = "RBS";
    public final static String RP = "RP";
    public final static String S = "S";
    public final static String SBAR = "SBAR";
    public final static String SBARQ = "SBARQ";
    public final static String SINV = "SINV";
    public final static String SQ = "SQ";
    public final static String SYM = "SYM";
    public final static String T = "T";
    public final static String TO = "TO";
    public final static String UH = "UH";
    public final static String VB = "VB";
    public final static String VBD = "VBD";
    public final static String VBG = "VBG";
    public final static String VBN = "VBN";
    public final static String VBP = "VBP";
    public final static String VBZ = "VBZ";
    public final static String VP = "VP";
    public final static String WDT = "WDT";
    public final static String WHADVP = "WHADVP";
    public final static String WHNP = "WHNP";
    public final static String WHPP = "WHPP";
    public final static String WP = "WP";
    public final static String WP$ = "WP$";
    public final static String WRB = "WRB";
    public final static String X = "X";

    public final static Map<String, String> TAGS;

    static {
        Map<String, String> tags = new HashMap<>();
        tags.put(ROOT, "The beginning of the sentence's structure");
        tags.put(ASTERICS, "\"Understood\" subject of infinitive or imperative");
        tags.put(ZERO, "Zero variant of that in subordinate clauses ");
        tags.put(ADJP, "Adjective phrase ");
        tags.put(ADVP, "Adverb phrase ");
        tags.put(CC, "Coordinating conjunction ");
        tags.put(CD, "Cardinal number ");
        tags.put(DT, "Determiner ");
        tags.put(EX, "Existential there ");
        tags.put(FW, "Foreign word ");
        tags.put(IN, "Preposition or subordinating conjunction ");
        tags.put(INTJ, "Interjection. Corresponds approximately to the part-of-speech tag UH.");
        tags.put(JJ, "Adjective ");
        tags.put(JJR, "Adjective, comparative ");
        tags.put(JJS, "Adjective, superlative ");
        tags.put(LS, "List item marker ");
        tags.put(MD, "Modal ");
        tags.put(NN, "Noun, singular or mass ");
        tags.put(NNP, "Proper noun, singular ");
        tags.put(NNPS, "Proper noun, plural ");
        tags.put(NNS, "Noun, plural ");
        tags.put(NP, "Noun phrase ");
        tags.put(PDT, "Predeterminer ");
        tags.put(POS, "Possessive ending ");
        tags.put(PP, "Prepositional phrase ");
        tags.put(PRP, "Personal pronoun ");
        tags.put(PRP$, "Possessive pronoun ");
        tags.put(RB, "Adverb ");
        tags.put(RBR, "Adverb, comparative ");
        tags.put(RBS, "Adverb, superlative ");
        tags.put(RP, "Particle ");
        tags.put(S, "Simple declarative clause ");
        tags.put(SBAR, "Subordinate clause ");
        tags.put(SBARQ, "Direct question introduced by wh-element ");
        tags.put(SINV, "Declarative sentence with subject-aux inversion ");
        tags.put(SQ, "Yes/no questions and subconstituent of SBARQ excluding wh-element ");
        tags.put(SYM, "Symbol ");
        tags.put(T, "Trace of wh-Constituent ");
        tags.put(TO, "to ");
        tags.put(UH, "Interjection ");
        tags.put(VB, "Verb, base form ");
        tags.put(VBD, "Verb, past tense ");
        tags.put(VBG, "Verb, gerund or present participle ");
        tags.put(VBN, "Verb, past participle ");
        tags.put(VBP, "Verb, non-3rd person singular present ");
        tags.put(VBZ, "Verb, 3rd person singular present ");
        tags.put(VP, "Verb phrase ");
        tags.put(WDT, "Wh-determiner ");
        tags.put(WHADVP, "Wh-adverb phrase ");
        tags.put(WHNP, "Wh-noun phrase ");
        tags.put(WHPP, "Wh-prepositional phrase ");
        tags.put(WP, "Wh-pronoun ");
        tags.put(WP$, "Possessive wh-pronoun ");
        tags.put(WRB, "Wh-adverb ");
        tags.put(X, "Constituent of unknown or uncertain category ");
        TAGS = Collections.unmodifiableMap(tags);
    }
}
